### ISSUE TITLE
train_order_info数据集

### ISSUE THREAD

**Issue by Choven-Meng** [chenkkkk/User-loan-risk-prediction#1]
请问提供的百度网盘中的数据集是否是原数据集？
train_order_info数据集中的time_order列的时间数据有些问题，该列的数据不仅有“Y-M-D H:M:S”和‘NA’格式的，还有69594 条数据是1479813954、1444574500、1453267153等这种的

**Comment by chenkkkk** [comment]
这是官方提供的原始数据集。至于时间格式中的1479813954、1444574500、1453267153数字，应该是unix时间戳。

**Comment by RickPang** [comment]
您好，网盘中下载的测试集AI_Risk_data_Btest_V2.0和代码中的AI_risk_test_V3.0目录中的测试集一样吗？

**Comment by chenkkkk** [comment]
是一样的

Mr-Dou <notifications@github.com> 于2018年11月20日周二 下午2:47写道：
