### ISSUE TITLE
04094.py中有个循环语句请教

### ISSUE THREAD

**Issue by yxcswt** [chenkkkk/User-loan-risk-prediction#2]
idcard_result=[]
    for indexx,uu in enumerate(auth_idcard):
        if (str(auth_idcard[indexx])=='nan')|(str(user_idcard[indexx])=='nan'):
            idcard_result.append(0)
        elif(str(auth_idcard[indexx])!='nan')|(str(user_idcard[indexx])=='nan'):
            idcard_result.append(1)
        elif (str(auth_idcard[indexx])=='nan')|(str(user_idcard[indexx])!='nan'):
            idcard_result.append(2)
        else:
            ttt1=str(auth_idcard[indexx])[0]+str(auth_idcard[indexx])[-1]
            ttt2=str(user_idcard[indexx])[0]+str(user_idcard[indexx])[-1]
            if ttt1==ttt2:
                idcard_result.append(3)
            if ttt1!=ttt2:
                idcard_result.append(4)

第一个if 语句中 if (str(auth_idcard[indexx])=='nan')|(str(user_idcard[indexx])=='nan')可能会包含
 elif(str(auth_idcard[indexx])!='nan')|(str(user_idcard[indexx])=='nan')中的一些情况吧？就是会出现交集的情况，能跟我说一说吗

**Comment by yxcswt** [comment]
这样其中交集的部分列表标签可能就是根据数据的出现顺序形成列表最终形成客户标签？

**Comment by yxcswt** [comment]
例如第一个条件语句包含情况：
   a=nan b=nan
   a!=nan b=nan
   a=nan  b!=nan
 第二个条件语句包含情况：
     a!=nan b!=nan
     a!=nan b=nan
     a=nan b=nan

**Comment by chenkkkk** [comment]
这里的判断条件的确是写错了，当时这个比赛由几个同学一起完成。这里的确忘了检查。
应该是 与 条件，不应该是 或 条件。

**Comment by chenkkkk** [comment]
> 这样其中交集的部分列表标签可能就是根据数据的出现顺序形成列表最终形成客户标签？

这里形成的列表不是客户标签，这里只是做为一个类别特征。判断用户卡号是否相同。

**Comment by yxcswt** [comment]
> > 这样其中交集的部分列表标签可能就是根据数据的出现顺序形成列表最终形成客户标签？
> 
> 这里形成的列表不是客户标签，这里只是做为一个类别特征。判断用户卡号是否相同。

好的，谢谢你的回复
