### ISSUE TITLE
请教下 Hobyy中 1，2，3...这些分别代表什么？

### ISSUE THREAD

**Issue by lili1147** [chenkkkk/User-loan-risk-prediction#4]
我也是重邮的

**Comment by chenkkkk** [comment]
@lili1147 是数据表里面的字段吗?
如果在数据表中，那这个字段是官方给的，匿名类别特征

**Comment by lili1147** [comment]
@chenkkkk  谢谢师兄！ 还想请问下师兄有没有贷款这方面的其他数据集，有关联到社交，消费维度的，找了好久没有找到的。再次感谢师兄

**Comment by chenkkkk** [comment]
@lili1147 没有了，这方面的数据比较少

**Comment by lili1147** [comment]
> @lili1147 没有了，这方面的数据比较少
好的，谢谢师兄
